---
- name: K8s Infrastructure Management
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure PVC exists for database persistence
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: sqlite-pvc
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi

    - name: Verify K8s Deployment State
      kubernetes.core.k8s_info:
        kind: Deployment
        name: leave-app-deployment
      register: deploy_status

    - name: Print Debug Info
      debug:
        msg: "Deployment currently has {{ deploy_status.resources | length }} active resources."